#ifndef MSREAL_VGA_DRIVER_DRIVER_INCLUDE_POINT_H_
#define MSREAL_VGA_DRIVER_DRIVER_INCLUDE_POINT_H_

static struct Point
{
    unsigned int x,y;
};

#endif //MSREAL_VGA_DRIVER_DRIVER_INCLUDE_POINT_H_
